/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ProgrammRouteImport } from './routes/programm'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as CherryPlusRouteImport } from './routes/cherry-plus'
import { Route as AbstractsRouteImport } from './routes/abstracts'
import { Route as IndexRouteImport } from './routes/index'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammRoute = ProgrammRouteImport.update({
  id: '/programm',
  path: '/programm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const CherryPlusRoute = CherryPlusRouteImport.update({
  id: '/cherry-plus',
  path: '/cherry-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const AbstractsRoute = AbstractsRouteImport.update({
  id: '/abstracts',
  path: '/abstracts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/cherry-plus': typeof CherryPlusRoute
  '/committees': typeof CommitteesRoute
  '/dates': typeof DatesRoute
  '/organization': typeof OrganizationRoute
  '/program': typeof ProgramRoute
  '/programm': typeof ProgrammRoute
  '/registration': typeof RegistrationRoute
  '/sessions': typeof SessionsRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/cherry-plus': typeof CherryPlusRoute
  '/committees': typeof CommitteesRoute
  '/dates': typeof DatesRoute
  '/organization': typeof OrganizationRoute
  '/program': typeof ProgramRoute
  '/programm': typeof ProgrammRoute
  '/registration': typeof RegistrationRoute
  '/sessions': typeof SessionsRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/cherry-plus': typeof CherryPlusRoute
  '/committees': typeof CommitteesRoute
  '/dates': typeof DatesRoute
  '/organization': typeof OrganizationRoute
  '/program': typeof ProgramRoute
  '/programm': typeof ProgrammRoute
  '/registration': typeof RegistrationRoute
  '/sessions': typeof SessionsRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abstracts'
    | '/cherry-plus'
    | '/committees'
    | '/dates'
    | '/organization'
    | '/program'
    | '/programm'
    | '/registration'
    | '/sessions'
    | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abstracts'
    | '/cherry-plus'
    | '/committees'
    | '/dates'
    | '/organization'
    | '/program'
    | '/programm'
    | '/registration'
    | '/sessions'
    | '/sponsors'
  id:
    | '__root__'
    | '/'
    | '/abstracts'
    | '/cherry-plus'
    | '/committees'
    | '/dates'
    | '/organization'
    | '/program'
    | '/programm'
    | '/registration'
    | '/sessions'
    | '/sponsors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbstractsRoute: typeof AbstractsRoute
  CherryPlusRoute: typeof CherryPlusRoute
  CommitteesRoute: typeof CommitteesRoute
  DatesRoute: typeof DatesRoute
  OrganizationRoute: typeof OrganizationRoute
  ProgramRoute: typeof ProgramRoute
  ProgrammRoute: typeof ProgrammRoute
  RegistrationRoute: typeof RegistrationRoute
  SessionsRoute: typeof SessionsRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programm': {
      id: '/programm'
      path: '/programm'
      fullPath: '/programm'
      preLoaderRoute: typeof ProgrammRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cherry-plus': {
      id: '/cherry-plus'
      path: '/cherry-plus'
      fullPath: '/cherry-plus'
      preLoaderRoute: typeof CherryPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abstracts': {
      id: '/abstracts'
      path: '/abstracts'
      fullPath: '/abstracts'
      preLoaderRoute: typeof AbstractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbstractsRoute: AbstractsRoute,
  CherryPlusRoute: CherryPlusRoute,
  CommitteesRoute: CommitteesRoute,
  DatesRoute: DatesRoute,
  OrganizationRoute: OrganizationRoute,
  ProgramRoute: ProgramRoute,
  ProgrammRoute: ProgrammRoute,
  RegistrationRoute: RegistrationRoute,
  SessionsRoute: SessionsRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
